#!/bin/bash

FILE=$1
SDUMP_OPT="-f"
MUDRAW_OPT="-o - -F png"

INDEX=1 # page origin:1
PAGES=`mutool info $FILE | grep "^Pages:" | cut -d" " -f2 `

tput civis
tput clear

echo "filename:$FILE page:$INDEX"
mutool draw $MUDRAW_OPT $FILE $INDEX 2> /dev/null | sdump $SDUMP_OPT 2> /dev/null

while :; do
	read -s -n 1 KEY

	tput clear

	case "$KEY" in
	"j")
		INDEX=`expr $INDEX + 1`;;
	"J")
		INDEX=`expr $INDEX + 10`;;
	"k")
		INDEX=`expr $INDEX - 1`;;
	"K")
		INDEX=`expr $INDEX - 10`;;
	"g")
		INDEX=1;;
	"G")
		INDEX=$PAGES;;
	"q")
		tput cnorm
		exit 0;;
	esac

	if test $INDEX -lt "1"; then
		INDEX=$PAGES
	elif test $INDEX -gt $PAGES; then
		INDEX=1
	fi

	echo "filename:$FILE page:$INDEX"
	mudraw $MUDRAW_OPT $FILE $INDEX 2> /dev/null | sdump $SDUMP_OPT 2> /dev/null
done
