#!/bin/bash

SDUMP_OPT="-f"
FILE=$1
INDEX=1

function mktemp_file()
{
	FILENAME=`mktemp /tmp/spdf.XXXXXX`
	mudraw -o $FILENAME -F png $1 $2 2> /dev/null
	echo $FILENAME
}

tput civis
tput clear

echo "filename:$FILE page:$INDEX"
PDF_IMAGE=`mktemp_file $FILE $INDEX`
if test -f $PDF_IMAGE; then
	sdump "$SDUMP_OPT" "$PDF_IMAGE" 2> /dev/null
	rm $PDF_IMAGE
fi

while :; do
	read -s -n 1 KEY

	#tput cr
	#tput el
	#tput cup 0 0
	tput clear

	case "$KEY" in
	"j")
		INDEX=`expr $INDEX + 1`;;
	"J")
		INDEX=`expr $INDEX + 10`;;
	"k")
		INDEX=`expr $INDEX - 1`;;
	"K")
		INDEX=`expr $INDEX - 10`;;
	"q")
		tput cnorm
		exit 0;;
	esac

	if test $INDEX -lt "1"; then
		INDEX=1
	fi

	#echo $INDEX
	echo "filename:$FILE page:$INDEX"
	PDF_IMAGE=`mktemp_file $FILE $INDEX`
	if test -f $PDF_IMAGE; then
		sdump "$SDUMP_OPT" "$PDF_IMAGE" 2> /dev/null
		rm $PDF_IMAGE
	fi
done
