#!/bin/bash

SDUMP_OPT="-f"
FILES=($@)
INDEX=0

#echo "file num: ${#FILES[@]}"
if test ${#FILES[@]} -le "0"; then
	exit 0
fi

tput civis # set cursor hidden
tput clear # clear screen and move to (0, 0)

echo "filename:${FILES[$INDEX]}"
#echo -ne "\ekfilename:${FILES[$INDEX]}\e\\" # xterm like title change
sdump "$SDUMP_OPT" "${FILES[$INDEX]}" 2> /dev/null

while :; do
	read -s -n 1 KEY

	tput clear # clear screen and move to (0, 0)

	case "$KEY" in
	"j")
		INDEX=`expr $INDEX + 1`;;
	"J")
		INDEX=`expr $INDEX + 10`;;
	"k")
		INDEX=`expr $INDEX - 1`;;
	"K")
		INDEX=`expr $INDEX - 10`;;
	"q")
		tput cnorm # set cursor visible
		exit 0;;
	esac

	if test $INDEX -lt "0"; then
		INDEX=`expr ${#FILES[@]} - 1`
	elif test $INDEX -ge "${#FILES[@]}"; then
		INDEX=0
	fi

	echo "filename:${FILES[$INDEX]}"
	#echo -ne "\ekfilename:${FILES[$INDEX]}\e\\" # xterm like title change
	sdump "$SDUMP_OPT" "${FILES[$INDEX]}" 2> /dev/null
done
